In [18]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a), a.ndim, a.shape, sep='\n')
#ndim : number of array dimensions
#shape : Tuple of array dimesions

b = np.array([[1, 2, 3], [4, 5, 6]]) #2차원 배열 생성
print(type(b), b.ndim, b.shape, sep='\n')
print(b[0,0], b[0, 1], b[1,0]) # 1 2 4

#모든 값이 0인 배열 생성
z = np.zeros((2,2))
print(z)

#모든 값이 특정 상수인 배열 생성
c = np.full((3, 3), 10)
print(c, type(c))


<class 'numpy.ndarray'>
1
(3,)
<class 'numpy.ndarray'>
2
(2, 3)
1 2 4
[[ 0.  0.]
 [ 0.  0.]]
[[ 10.  10.  10.]
 [ 10.  10.  10.]
 [ 10.  10.  10.]] <class 'numpy.ndarray'>


C:\ProgramData\Anaconda3\envs\Python3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((3, 3), 10) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
